version: '3'
services:
  poster-mongo:
    image: mongo:latest
    container_name: poster-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    env_file:
      - .env
  poster-redis:
    image: redis:latest
    container_name: poster-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - .env
  poster-backend:
    image: ccr.ccs.tencentyun.com/minorn/poster:0.0.1
    container_name: poster-backend
    ports:
      - 7001:7001
    env_file:
      - .env